### ISSUE TITLE
Clicking a footnote link does nothing

### ISSUE THREAD

**Issue by sevenseacat** [radar/twist-v2#8] opened 2020-02-26 15:16 UTC
eg. the [1] on https://twistbooks.com/books/rails-book/chapters/ruby-on-rails-the-framework

Adds the hash `#_footnotedef_1` to the URL, but nothing else happens - I assume there's supposed to be a tooltip or popup with the footnote text?

No errors in JS console.

Tested on OSX using Firefox 73.0.1.

**Comment by radar** [comment] 2020-02-26 21:59
Bit of a tricky one because footnote text is outside the chapter element...

But if I parse footnotes first then chapter elems then it’ll be alright.

I’ve got half a patch made up today on the train. I’ll see about finishing it tonight.

**Comment by sevenseacat** [comment] 2020-02-27 01:40
I didn't even know there was a v2 repo. My bad. Cheers :)

**Comment by radar** [comment] 2020-02-27 01:58
V1 is a rails app. But because I’m living in Melbourne now I have to hand craft and bespoke the shit out of everything, so hence v2

**Comment by sevenseacat** [comment] 2020-03-03 09:13
Something still seems to be a bit wonky with footnotes. eg. in https://twistbooks.com/books/rails-book/chapters/ruby-on-rails-the-framework footnote counting starts at 1, but the footnote list at the bottom of the page starts at 8.

**Comment by radar** [comment] 2020-03-07 09:18
![image](https://user-images.githubusercontent.com/2687/76140629-b5461100-60b0-11ea-91df-003bbd532135.png)

Yup, something's stuffed there. It should be a contiguous list from 1-16. It's like it's skipping some. I'll try to figure out why.

**Comment by radar** [comment] 2020-03-07 09:52
I suspect this was caused by a bug where footnotes were wiped when chapters were deleted (as a part of the regular update cycle). This was due to a misconfigured foreign key on footnotes:

This commit corrects that mistake: https://github.com/radar/twist-v2/commit/4b887d414b78645c61c1fbea6eef9692edd2aa94

Footnotes are now no longer deleted when the chapters are.

**Comment by radar** [comment] 2020-03-07 09:57
![image](https://user-images.githubusercontent.com/2687/76141223-4370c600-60b6-11ea-9de1-000ca125ab73.png)

Good news: All the footnotes appear. 

Bad news: they're out of order.

**Comment by radar** [comment] 2020-03-08 08:11
I think these particular brand of footnote issues are now fixed. Please open a new issue if you see others.

**Closed by radar** 2020-03-08 08:11 UTC
